/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { memo, useMemo } from "react"
import { useGLTF } from "@react-three/drei"
import { MeshStandardMaterial } from "three"
import { useCharacterAnimationsStore } from "../../stores/useCharacterAnimationsStore"

const Chair = (props) => {
  const { nodes } = useGLTF("/models/chair.glb", "/draco/")

  // ✅ subscribe only to what you need
  const animation = useCharacterAnimationsStore((s) => s.animation)

  // ✅ single material instance
  const chairMaterial = useMemo(
    () => new MeshStandardMaterial({ color: "black" }),
    []
  )

  return (
    <group
      {...props}
      dispose={null}
      position={[0, 0, animation === "typing" ? 0 : -0.7]}
    >
      <mesh
        geometry={nodes.chair.geometry}
        material={chairMaterial}
        position={[-0.001, 0.622, -0.094]}
      />
      <mesh
        geometry={nodes.chair001.geometry}
        material={chairMaterial}
        position={[-0.001, 0.11, 0.099]}
      />
      <mesh
        geometry={nodes.chair002.geometry}
        material={chairMaterial}
        position={[-0.003, 0.03, 0.099]}
      />
    </group>
  )
}

useGLTF.preload("/models/chair.glb", "/draco/")
export default memo(Chair)
