/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { memo, useMemo } from "react"
import { useGLTF } from "@react-three/drei"
import { MeshStandardMaterial } from "three"

const Desk = (props) => {
  const { nodes } = useGLTF("/models/desk.glb", "/draco/")

  // ✅ materials created once
  const surfaceMaterial = useMemo(
    () => new MeshStandardMaterial({ color: "gray" }),
    []
  )

  const legsMaterial = useMemo(
    () => new MeshStandardMaterial({ color: "silver" }),
    []
  )

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Desk_Surface.geometry}
        material={surfaceMaterial}
        position={[-0.004, 0.827, -0.004]}
        rotation={[-Math.PI, 0.002, 0]}
        scale={[0.811, 0.018, 0.405]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk_Legs.geometry}
          material={legsMaterial}
          position={[0, 23.64, 0]}
          scale={[0.964, 22.773, 0.929]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload("/models/desk.glb", "/draco/")
export default memo(Desk)
