/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { memo, useEffect, useMemo, useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import * as THREE from "three"
import { DoubleSide, MeshStandardMaterial } from "three"
import { RectAreaLightUniformsLib } from "three/examples/jsm/lights/RectAreaLightUniformsLib"
import { useGraphicsSettings } from "../../stores/useGraphicsSettings"
import { useCharacterAnimationsStore } from "../../stores/useCharacterAnimationsStore"
import { mouseInteractionRef } from "./Mouse"

export const monitorTypingRef = { current: false }

// ✅ init once (module scope)
RectAreaLightUniformsLib.init()

const CODE_LINES = [
  "import * as THREE from 'three'",
  "import { OrbitControls } from 'three/addons/controls/OrbitControls.js'",
  "",
  "const scene = new THREE.Scene()",
  "scene.background = new THREE.Color('#0d1117')",
  "",
  "const camera = new THREE.PerspectiveCamera(45, width / height, 0.1, 100)",
  "camera.position.set(3, 2, 5)",
  "",
  "const renderer = new THREE.WebGLRenderer({ antialias: true })",
  "renderer.setPixelRatio(Math.min(devicePixelRatio, 1.5))",
  "renderer.setSize(width, height)",
  "",
  "const controls = new OrbitControls(camera, renderer.domElement)",
  "controls.enableDamping = true",
  "",
  "const geometry = new THREE.IcosahedronGeometry(1, 3)",
  "const material = new THREE.MeshStandardMaterial({",
  "  color: '#58a6ff',",
  "  roughness: 0.25,",
  "  metalness: 0.65,",
  "})",
  "const mesh = new THREE.Mesh(geometry, material)",
  "scene.add(mesh)",
  "",
  "const light = new THREE.DirectionalLight('#ffffff', 3)",
  "light.position.set(4, 5, 2)",
  "scene.add(light, new THREE.AmbientLight('#6688aa', 0.5))",
  "",
  "function animate() {",
  "  requestAnimationFrame(animate)",
  "  mesh.rotation.y += 0.006",
  "  mesh.rotation.x += 0.002",
  "  controls.update()",
  "  renderer.render(scene, camera)",
  "}",
  "",
  "animate()",
]

const CODE_TEXT = CODE_LINES.join("\n")
const SCREEN_WIDTH = 768
const SCREEN_HEIGHT = 384
const MAX_VISIBLE_CODE_LINES = 12
const TERMINAL_MESSAGES = [
  "Compiled successfully. Suspicious.",
  "1 bug created, 0 fixed.",
  "It works on my machine.",
  "Deploying confidence...",
]

const drawCodingScreen = (context, characterCount, elapsed) => {
  context.fillStyle = "#0d1117"
  context.fillRect(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT)

  context.fillStyle = "#161b22"
  context.fillRect(0, 0, SCREEN_WIDTH, 32)
  context.fillStyle = "#21262d"
  context.fillRect(0, 32, 40, SCREEN_HEIGHT - 32)

  context.font = "13px monospace"
  context.fillStyle = "#8b949e"
  context.fillText("●  ●  ●", 12, 21)
  context.fillStyle = "#c9d1d9"
  context.fillText("Experience.jsx  ×", 280, 21)

  context.fillStyle = "#58a6ff"
  context.fillRect(0, 32, 3, 42)
  context.fillStyle = "#8b949e"
  context.font = "18px monospace"
  context.fillText("◇", 11, 58)
  context.fillText("⌕", 11, 90)
  context.fillText("⑂", 11, 122)

  const visibleText = CODE_TEXT.slice(0, characterCount)
  const visibleLines = visibleText.split("\n")
  const scrollStart = Math.max(0, visibleLines.length - MAX_VISIBLE_CODE_LINES)
  const displayedLines = visibleLines.slice(scrollStart)
  const lineHeight = 21
  const startY = 54

  context.font = "14px monospace"
  for (let i = 0; i < displayedLines.length; i += 1) {
    const y = startY + i * lineHeight
    context.fillStyle = "#6e7681"
    context.fillText(String(scrollStart + i + 1).padStart(2, " "), 46, y)

    const line = displayedLines[i]
    context.fillStyle = line.includes("function")
      ? "#d2a8ff"
      : line.includes("THREE")
        ? "#79c0ff"
        : line.includes("render") || line.includes("animate")
          ? "#7ee787"
          : "#c9d1d9"
    context.fillText(line, 76, y)
  }

  const lastLine = visibleLines[visibleLines.length - 1] || ""
  const cursorX = 76 + context.measureText(lastLine).width + 2
  const cursorY = startY + (displayedLines.length - 1) * lineHeight
  if (Math.floor(elapsed * 2) % 2 === 0) {
    context.fillStyle = "#58a6ff"
    context.fillRect(cursorX, cursorY - 18, 3, 22)
  }

  const autocompletePhase = elapsed % 14
  if (autocompletePhase > 5 && autocompletePhase < 7.2 && cursorY < 260) {
    const popupX = Math.min(cursorX + 8, 520)
    const popupY = cursorY + 7
    context.fillStyle = "#161b22"
    context.fillRect(popupX, popupY, 180, 65)
    context.strokeStyle = "#30363d"
    context.strokeRect(popupX, popupY, 180, 65)
    context.fillStyle = "#1f6feb"
    context.fillRect(popupX + 2, popupY + 2, 176, 19)
    context.font = "12px monospace"
    context.fillStyle = "#ffffff"
    context.fillText("◇ render", popupX + 9, popupY + 16)
    context.fillStyle = "#c9d1d9"
    context.fillText("◇ requestAnimationFrame", popupX + 9, popupY + 37)
    context.fillText("◇ renderer", popupX + 9, popupY + 56)
  }

  // Compact minimap and terminal make the screen feel like a live editor.
  context.globalAlpha = 0.35
  for (let i = 0; i < CODE_LINES.length; i += 1) {
    context.fillStyle = i % 3 === 0 ? "#79c0ff" : "#8b949e"
    context.fillRect(690, 48 + i * 7, 35 + (i % 4) * 8, 2)
  }
  context.globalAlpha = 1

  context.fillStyle = "#0b0f14"
  context.fillRect(40, 310, SCREEN_WIDTH - 40, 52)
  context.fillStyle = "#30363d"
  context.fillRect(40, 310, SCREEN_WIDTH - 40, 1)
  context.fillRect(500, 310, 1, 52)

  context.font = "10px monospace"
  context.fillStyle = "#8b949e"
  context.fillText("TERMINAL", 55, 322)
  context.fillText("DEV NOTES", 515, 322)

  context.font = "11px monospace"
  context.fillStyle = "#c9d1d9"
  context.fillText("$ vite --host", 55, 339)
  context.fillStyle = "#7ee787"
  context.fillText("ready in 428 ms  Local: localhost:5173", 55, 354)

  const terminalMessage =
    TERMINAL_MESSAGES[Math.floor(elapsed / 8) % TERMINAL_MESSAGES.length]
  context.font = "10px monospace"
  context.fillStyle = "#d2a8ff"
  context.fillText(terminalMessage, 515, 345)

  context.globalAlpha = 0.08
  context.fillStyle = "#58a6ff"
  context.fillRect(40, 32 + ((elapsed * 45) % 278), SCREEN_WIDTH - 40, 2)
  context.globalAlpha = 1

  context.fillStyle = "#1f6feb"
  context.fillRect(0, SCREEN_HEIGHT - 22, SCREEN_WIDTH, 22)
  context.fillStyle = "#ffffff"
  context.font = "13px monospace"
  context.fillText(
    "pretending-to-work*   Ln 36, Col 1     UTF-8     JavaScript",
    16,
    SCREEN_HEIGHT - 7,
  )
}

const useCodingScreen = (quality, isWorking) => {
  const renderedLastFrameRef = useRef(true)
  const updateRef = useRef({ lastTime: -1, lastCharacterCount: -1 })
  const screenTimeRef = useRef(0)
  const screen = useMemo(() => {
    const canvas = document.createElement("canvas")
    canvas.width = SCREEN_WIDTH
    canvas.height = SCREEN_HEIGHT
    const context = canvas.getContext("2d")
    const texture = new THREE.CanvasTexture(canvas)
    texture.colorSpace = THREE.SRGBColorSpace
    texture.flipY = false
    texture.wrapS = THREE.RepeatWrapping
    texture.repeat.x = -1
    texture.offset.x = 1
    texture.minFilter = THREE.LinearFilter
    texture.magFilter = THREE.LinearFilter
    drawCodingScreen(context, 0, 0)
    texture.needsUpdate = true
    return { context, texture }
  }, [])

  useEffect(() => () => screen.texture.dispose(), [screen])

  useFrame((_, delta) => {
    const wasRendered = renderedLastFrameRef.current
    renderedLastFrameRef.current = false
    if (!wasRendered || !isWorking || mouseInteractionRef.current) {
      monitorTypingRef.current = false
      return
    }

    screenTimeRef.current += Math.min(delta, 0.1)
    const elapsed = screenTimeRef.current
    const typingDuration = CODE_TEXT.length / 22
    const loopDuration = typingDuration + 4
    const loopTime = elapsed % loopDuration
    monitorTypingRef.current = loopTime < typingDuration
    const interval =
      quality === "high" ? 1 / 20 : quality === "medium" ? 1 / 15 : 1 / 10
    if (elapsed - updateRef.current.lastTime < interval) return

    const naturalTypingPosition =
      loopTime * 22 + Math.sin(loopTime * 2.4) * 2 + Math.sin(loopTime * 0.7) * 3
    const characterCount = Math.min(
      Math.max(0, Math.floor(naturalTypingPosition)),
      CODE_TEXT.length,
    )
    const cursorChanged = Math.floor(elapsed * 2) !== Math.floor(updateRef.current.lastTime * 2)
    if (characterCount === updateRef.current.lastCharacterCount && !cursorChanged) return

    updateRef.current.lastTime = elapsed
    updateRef.current.lastCharacterCount = characterCount
    drawCodingScreen(screen.context, characterCount, elapsed)
    screen.texture.needsUpdate = true
  })

  return { texture: screen.texture, renderedLastFrameRef }
}

const Monitor2 = (props) => {
  const { nodes } = useGLTF("/models/monitor2.glb", "/draco/")
  const quality = useGraphicsSettings((s) => s.quality)
  const animation = useCharacterAnimationsStore((s) => s.animation)
  const { texture: codingTexture, renderedLastFrameRef } = useCodingScreen(
    quality,
    animation === "typing",
  )

  // ✅ memoized materials (single GPU allocation)
  const bodyMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: "#eeeeee",
        side: DoubleSide,
        roughness: 0.1,
        metalness: 1,
      }),
    []
  )

  const frameMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: "#eeeeee",
        side: DoubleSide,
        roughness: 0,
        metalness: 1,
      }),
    []
  )

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={bodyMaterial}
        position={[0.003, 0.007, 0.006]}
        rotation={[-1.497, -1.56, -1.51]}
        scale={0.12}
      />

      <group
        position={[0.007, 0.397, -0.006]}
        rotation={[-1.497, -1.56, -1.598]}
        scale={[0.21, 0.14, 0.2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={frameMaterial}
        />

        <mesh
          geometry={nodes.Plane006_1.geometry}
          onBeforeRender={() => {
            renderedLastFrameRef.current = true
          }}
        >
          <meshBasicMaterial
            map={codingTexture}
            toneMapped={false}
            side={DoubleSide}
          />
        </mesh>

        <rectAreaLight
          color="#ffffff"
          intensity={8}
          width={0.4}
          height={0.25}
          rotation={[-Math.PI, Math.PI / 2, Math.PI]}
          position={[-0.1, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/monitor2.glb", "/draco/")
export default memo(Monitor2)
