/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { memo, useMemo } from "react"
import { useGLTF } from "@react-three/drei"
import { DoubleSide, MeshStandardMaterial } from "three"
import { RectAreaLightUniformsLib } from "three/examples/jsm/lights/RectAreaLightUniformsLib"

// ✅ init once (module scope)
RectAreaLightUniformsLib.init()

const Monitor2 = (props) => {
  const { nodes, materials } = useGLTF("/models/monitor2.glb", "/draco/")

  // ✅ memoized materials (single GPU allocation)
  const bodyMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: "#eeeeee",
        side: DoubleSide,
        roughness: 0.1,
        metalness: 1,
      }),
    []
  )

  const frameMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: "#eeeeee",
        side: DoubleSide,
        roughness: 0,
        metalness: 1,
      }),
    []
  )

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={bodyMaterial}
        position={[0.003, 0.007, 0.006]}
        rotation={[-1.497, -1.56, -1.51]}
        scale={0.12}
      />

      <group
        position={[0.007, 0.397, -0.006]}
        rotation={[-1.497, -1.56, -1.598]}
        scale={[0.21, 0.14, 0.2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={frameMaterial}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials["Screen.001"]}
        />

        <rectAreaLight
          color="#ffffff"
          intensity={8}
          width={0.4}
          height={0.25}
          rotation={[-Math.PI, Math.PI / 2, Math.PI]}
          position={[-0.1, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/monitor2.glb", "/draco/")
export default memo(Monitor2)
