import React from "react";

const Taha = ({ charRef, nodes, materials }) => {
  return (
    <group
      receiveShadow
      castShadow
      ref={charRef}
      dispose={null}
      frustumCulled={false}
    >
      <group receiveShadow castShadow name="Scene" frustumCulled={false}>
        <group
          receiveShadow
          castShadow
          name="Armature001"
          frustumCulled={false}
        >
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={materials["Wolf3D_Eye.011"]}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={materials["Wolf3D_Eye.011"]}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials["Wolf3D_Body.011"]}
            skeleton={nodes.Wolf3D_Body.skeleton}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Glasses"
            geometry={nodes.Wolf3D_Glasses.geometry}
            material={materials["Wolf3D_Glasses.011"]}
            skeleton={nodes.Wolf3D_Glasses.skeleton}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials["Wolf3D_Hair.011"]}
            skeleton={nodes.Wolf3D_Hair.skeleton}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials["Wolf3D_Skin.011"]}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials["Wolf3D_Outfit_Bottom.011"]}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials["Wolf3D_Outfit_Footwear.011"]}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top001"
            geometry={nodes.Wolf3D_Outfit_Top001.geometry}
            material={materials["Wolf3D_Outfit_Top.011"]}
            skeleton={nodes.Wolf3D_Outfit_Top001.skeleton}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials["Wolf3D_Teeth.011"]}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
          <primitive object={nodes.Hips} />
        </group>
      </group>
    </group>
  );
};

export default React.memo(Taha);
