/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";
import { wallHeight } from "../../constances/constances";

const Luster = (props) => {
  const { nodes, materials } = useGLTF("/models/luster.glb");
  const [lampIsOn, setLampIsOn] = useState(true);
  const shinyEmissiveMaterial = new MeshStandardMaterial({
    color: 0xffaaaa, // white base color
    roughness: 0.1, // low roughness for shininess
    metalness: 0.9, // high metalness for reflective look
    emissive: 0xffaaaa, // light yellow emissive color
    emissiveIntensity: lampIsOn ? 4 : 0, // intensity of the emissive color
    clipShadows: false,
  });

  const handleOnClick = () => {
    setLampIsOn(!lampIsOn);
  };

  return (
    <group {...props} dispose={null} onClick={handleOnClick}>
      <directionalLight
        position={[0, wallHeight, 0]}
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        intensity={lampIsOn ? 2 : 0}
      />
      <group rotation={[-Math.PI, 0, 0]} scale={0.025}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.Body} />
        <mesh
          geometry={nodes.Mesh_1.geometry}
          material={shinyEmissiveMaterial}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/luster.glb");
export default Luster;
