/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { MeshStandardMaterial } from "three";
const ReactIcon = (props) => {
  const { nodes, materials } = useGLTF("/models/react.glb", "/draco/");
  const reactIconRef = useRef();
  useFrame(({ clock }) => {
    reactIconRef.current.rotation.y = clock.getElapsedTime() * -0.02;
  });
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.0, 0]} scale={[0.9, 0.09, 0.9]}>
        {/* <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.002"]}
          /> */}
        <mesh
          ref={reactIconRef}
          geometry={nodes.Cylinder_1.geometry}
          material={new MeshStandardMaterial({ color: "#67dcfb" })}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/react.glb", "/draco/");

export default ReactIcon;
