/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Cat = (props) => {
  const { nodes, materials } = useGLTF("/models/cat.glb");
  return (
    <group {...props} dispose={null} position={[0, 0, 3]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cat.geometry}
        material={materials["01 - Default"]}
      />
    </group>
  );
};

useGLTF.preload("/models/cat.glb");

export default Cat;
