/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";

export const Cat2 = (props) => {
  const { nodes, materials } = useGLTF('/models/cat2.glb')
  return (
    <group {...props} dispose={null} scale={0.5}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gato001.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gato001_1.geometry}
        material={materials['Material.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gato001_2.geometry}
        material={materials['Material.005']}
      />
    </group>
  )
}

useGLTF.preload("/models/cat.glb");

export default Cat2;
