/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCharacterAnimations } from "../contexts/CharacterAnimations";
import { MeshStandardMaterial } from "three";

const Chair = (props) => {
  const { nodes, materials } = useGLTF("/models/chair.glb");
  const { animation } = useCharacterAnimations();
  useEffect(() => {}, [animation]);
  return (
    <group
      {...props}
      dispose={null}
      position={[0, 0, animation === "typing" ? 0 : -0.7]}
    >
      <mesh
        geometry={nodes.chair.geometry}
        material={new MeshStandardMaterial({ color: "black" })}
        position={[-0.001, 0.622, -0.094]}
      />
      <mesh
        geometry={nodes.chair001.geometry}
        material={new MeshStandardMaterial({ color: "black" })}
        position={[-0.001, 0.11, 0.099]}
      />
      <mesh
        geometry={nodes.chair002.geometry}
        material={new MeshStandardMaterial({ color: "black" })}
        position={[-0.003, 0.03, 0.099]}
      />
    </group>
  );
};

useGLTF.preload("/models/chair.glb");

export default Chair;
