/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Chair = (props) => {
  const { nodes, materials } = useGLTF("/models/chair.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair.geometry}
        material={materials["Material.001"]}
        position={[-0.001, 0.622, -0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair001.geometry}
        material={materials["Material.002"]}
        position={[-0.001, 0.11, 0.099]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair002.geometry}
        material={materials["Material.001"]}
        position={[-0.003, 0.03, 0.099]}
      />
    </group>
  );
};

useGLTF.preload("/models/chair.glb");

export default Chair;
