/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

const Desk = (props) => {
  const { nodes, materials } = useGLTF("/models/desk.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        
        
        geometry={nodes.Desk_Surface.geometry}
        material={
          new MeshStandardMaterial({ color: 'gray' })
        }        position={[-0.004, 0.827, -0.004]}
        rotation={[-Math.PI, 0.002, 0]}
        scale={[0.811, 0.018, 0.405]}
      >
        <mesh
          geometry={nodes.Desk_Legs.geometry}
          material={
            new MeshStandardMaterial({ color: 'silver' })
          }
          position={[0, 23.64, 0]}
          scale={[0.964, 22.773, 0.929]}
        />
      </mesh>
    </group>
  );
};

useGLTF.preload("/models/desk.glb");
export default Desk;
