/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Desk = (props) => {
  const { nodes, materials } = useGLTF("/models/desk.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Desk_Surface.geometry}
        material={materials.Material}
        position={[-0.004, 0.827, -0.004]}
        rotation={[-Math.PI, 0.002, 0]}
        scale={[0.811, 0.018, 0.405]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk_Legs.geometry}
          material={materials['Material.001']}
          position={[0, 23.64, 0]}
          scale={[0.964, 22.773, 0.929]}
        />
      </mesh>
    </group>
  )
};

useGLTF.preload("/models/desk.glb");
export default Desk;
