/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Keyboard = (props) => {
  const { nodes, materials } = useGLTF("/models/keyboard.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.003, 0.027, -0.01]}
        rotation={[-0.072, -0.003, 0]}
        scale={[0.146, 0.217, 0.146]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_1.geometry}
          material={materials.Материал}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_2.geometry}
          material={materials['Материал.033']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_3.geometry}
          material={materials['Материал.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_4.geometry}
          material={materials['Материал.036']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_5.geometry}
          material={materials['Материал.014']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_6.geometry}
          material={materials['Материал.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_7.geometry}
          material={materials['Материал.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_8.geometry}
          material={materials['Материал.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_9.geometry}
          material={materials['Материал.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_10.geometry}
          material={materials['Материал.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_11.geometry}
          material={materials['Материал.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube412_12.geometry}
          material={materials['Материал.016']}
        />
      </group>
    </group>
  )
};

useGLTF.preload("/models/keyboard.glb");

export default Keyboard;
