/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { wallHeight } from "./Walls";

const Luster = (props) => {
  const { nodes, materials } = useGLTF("/models/luster.glb");
  
  return (
    <group {...props} dispose={null}>
      <directionalLight
        position={[0, wallHeight, 0]}
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        intensity={1}
      />
      <group rotation={[-Math.PI, 0, 0]} scale={0.025}>
        <mesh
          geometry={nodes.Mesh.geometry}
          material={materials.Body}
        />
        <mesh
          geometry={nodes.Mesh_1.geometry}
          material={materials.Light}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/luster.glb");
export default Luster;
