/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { DoubleSide, MeshStandardMaterial } from "three";

const Monitor2 = (props) => {
  const { nodes, materials } = useGLTF("/models/monitor2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        
        geometry={nodes.Plane.geometry}
        material={
          new MeshStandardMaterial({
            color: "#eeeeee",
            side: DoubleSide,
            roughness: 0.1,
            metalness: 1
          })
        }
        position={[0.003, 0.007, 0.006]}
        rotation={[-1.497, -1.56, -1.51]}
        scale={0.144}
      />
      <group
        position={[0.007, 0.397, -0.006]}
        rotation={[-1.497, -1.56, -1.598]}
        scale={[0.21, 0.16, 0.2]}>
        <mesh
          castShadow
          receiveShadow
          
          geometry={nodes.Plane006.geometry}
          material={
            new MeshStandardMaterial({
              color: "#eeeeee",
              side: DoubleSide,
              roughness: 0,
              metalness: 1
            })
          }
        />
        <mesh
          castShadow
          receiveShadow
          
          geometry={nodes.Plane006_1.geometry}
          material={materials['Screen.001']}
        />
      </group>
    </group>
  )
};

useGLTF.preload("/models/monitor2.glb");

export default Monitor2;
