/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
const ReactIcon = (props) => {
  const { nodes, materials } = useGLTF('/models/react.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.049, 0]} scale={[0.7, 0.09, 0.7]}>
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cylinder_1.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/react.glb')

export default ReactIcon;