/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
const ReactIcon = (props) => {
  const { nodes, materials } = useGLTF("/models/react.glb");
  const reactIconRef = useRef();
  useFrame(({ clock }) => {
    reactIconRef.current.rotation.y = clock.getElapsedTime() * -0.3;
  });
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.049, 0]} scale={[0.9, 0.09, 0.9]}>
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.002"]}
          />
        <mesh
          ref={reactIconRef}
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/react.glb");

export default ReactIcon;
