/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useCharacterAnimations } from "../contexts/CharacterAnimations";

const Taha = (props) => {
  const group = useRef();
  const currentAction = useRef("");
  const { nodes, materials, animations } = useGLTF("/models/Taha.glb");
  const { actions, names } = useAnimations(animations, group);
  const { setAnimations, animation, setAnimation } = useCharacterAnimations();

  setAnimations(names);
  useEffect(() => {
    if (currentAction.current !== actions[animation]) {
      const nextActionToPlay = actions[animation];
      const current = actions[currentAction.current];
      current?.fadeOut(0.2);
      nextActionToPlay?.reset().fadeIn(0.2).play();
      currentAction.current = animation;
    }
  }, [animation, actions, names]);

  useEffect(() => {
    setAnimation("typing");
  }, []);

  return (
    <group ref={group} {...props} dispose={null} frustumCulled={false}>
      <group name="Scene" frustumCulled={false}>
        <group name="Armature001" frustumCulled={false}>
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={materials["Wolf3D_Eye.011"]}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
            frustumCulled={false}
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={materials["Wolf3D_Eye.011"]}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials["Wolf3D_Body.011"]}
            skeleton={nodes.Wolf3D_Body.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Wolf3D_Glasses"
            geometry={nodes.Wolf3D_Glasses.geometry}
            material={materials["Wolf3D_Glasses.011"]}
            skeleton={nodes.Wolf3D_Glasses.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials["Wolf3D_Hair.011"]}
            skeleton={nodes.Wolf3D_Hair.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials["Wolf3D_Skin.011"]}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials["Wolf3D_Outfit_Bottom.011"]}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials["Wolf3D_Outfit_Footwear.011"]}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top001"
            geometry={nodes.Wolf3D_Outfit_Top001.geometry}
            material={materials["Wolf3D_Outfit_Top.011"]}
            skeleton={nodes.Wolf3D_Outfit_Top001.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials["Wolf3D_Teeth.011"]}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
            frustumCulled={false}
          />
          <primitive object={nodes.Hips} />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/Taha.glb");

export default Taha;
